# Generated by Django 5.1.2 on 2024-10-23 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pationt_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('desease', models.CharField(max_length=20)),
                ('pationt_type', models.CharField(max_length=20)),
            ],
        ),
    ]
